management:
  endpoints:
    web:
      exposure:
        include: env

spring:
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB